name: Rego Policy Test

on:
  push:
    paths:
      - '**.rego'
      - 'data.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download OPA v0.11.0
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.11.0/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Run OPA tests
        run: opa test . --verbose
